# Generated by Django 3.1.3 on 2020-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0003_auto_20201213_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='plakaty'),
        ),
    ]
