# Generated by Django 3.1.3 on 2020-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0004_auto_20201213_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='opis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='rok',
            field=models.PositiveSmallIntegerField(blank=True, default=2000),
        ),
    ]
