# Generated by Django 3.1.3 on 2020-12-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0006_auto_20201215_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, null=True)),
                ('gwiazdki', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='dodatkowe',
        ),
        migrations.DeleteModel(
            name='DodatkoweInfo',
        ),
        migrations.AddField(
            model_name='ocena',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.film'),
        ),
        migrations.AddField(
            model_name='film',
            name='gatunek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.gatunek'),
        ),
    ]
